name = "AWSTools"
uuid = "83bcdc74-1232-581c-948a-f29122bf8259"
authors = ["Invenia Technical Computing"]
version = "1.7.4"

[deps]
AWSCore = "4f1ea46c-232b-54a6-9b17-cc2d0f3e6598"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
AWSCore = "0.5, 0.6"
AWSS3 = "0.6"
EzXML = "0.7.3, 0.8, 0.9, 1"
FilePathsBase = "0.6, 0.7, 0.8"
HTTP = "0.8.4"
MbedTLS = "0.6, 0.7, 1"
Memento = "0.12.1, 0.13, 1"
Mocking = "0.7"
OrderedCollections = "1"
XMLDict = "0.1.3, 0.2, 0.3, 0.4"
julia = "1"

[extras]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[targets]
test = ["HTTP", "Test", "UUIDs"]
